// classes / components
import { Livro } from "@/classes/modelo/Livro";
import { LinhaLivro } from "@/componentes/LinhaLivro";
import { Menu } from "@/componentes/Menu";

// React / Next
import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

// styles
import styles from "@/styles/Home.module.css";

const baseURL = "http://localhost:3000/api/livros";

const obter = async () => {
	const res = await fetch(baseURL);
	const data = await res.json();

	return data;
};

const excluirLivro = async (codigo: number) => {
	await fetch(`${baseURL}/${codigo}`, {
		method: "DELETE",
	})
		.then((result) => console.log("Sucesso!"))
		.catch((err) => console.log(err));
};

const LivroLista: NextPage = () => {
	const [livros, setLivros] = useState<Array<Livro>>();
	const [carregado, setCarregado] = useState(false);

	const excluir = (codigo: number) => {
		excluirLivro(codigo);

		setCarregado(false);
	};

	useEffect(() => {
		obter().then((result) => {
			setLivros(result);

			setCarregado(true);
		});
	}, [carregado]);

	return (
		<>
			<Head>
				<title>Loja Next</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Menu />

			<main className={styles.main}>
				<h1 className="title">Lista de Livros</h1>

				<table>
					<tbody>
						{livros?.map((livro) => {
							return (
								<LinhaLivro
									key={livro.codigo}
									livro={livro}
									excluir={excluir}
								/>
							);
						})}
					</tbody>
				</table>
			</main>
		</>
	);
};

export default LivroLista;
