// classes / components
import { Livro } from "@/classes/modelo/Livro";
import { LinhaLivro } from "@/componentes/LinhaLivro";
import { Menu } from "@/componentes/Menu";

// React / Next
import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

// styles
import styles from "@/styles/Home.module.css";
import { ControleLivro } from "@/classes/controle/ControleLivros";

const controleLivros = new ControleLivro();

const LivroLista: NextPage = () => {
	const [livros, setLivros] = useState<Array<Livro>>();
	const [carregado, setCarregado] = useState(false);

	const excluir = (codigo: string) => {
		controleLivros.excluir(codigo).then(() => setCarregado(false));
	};

	useEffect(() => {
		const obterTodos = async () => {
			await controleLivros.obterLivros().then((result) => {
				setLivros(result);

				setCarregado(true);
			});
		};

		obterTodos();
	}, [carregado]);

	return (
		<>
			<Head>
				<title>Loja Next</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Menu />

			<main className={styles.main}>
				<h1 className="title">Lista de Livros</h1>

				<table className="table">
					<thead className="table-dark">
						<tr>
							<th>Título</th>
							<th>Resumo</th>
							<th>Editora</th>
							<th>Autores</th>
						</tr>
					</thead>

					<tbody>
						{livros?.map((livro, index) => {
							return (
								<LinhaLivro
									key={index}
									livro={livro}
									excluir={excluir}
								/>
							);
						})}
					</tbody>
				</table>
			</main>
		</>
	);
};

export default LivroLista;
